context:
  version: "0.3.0"
  python_min: "3.11"

package:
  name: spaday-lightweight-charts
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/spaday-lightweight-charts/spaday_lightweight_charts-${{ version }}.tar.gz
  sha256: 7040af4c431d77f934198bab64410dae5be73dc4320e6cb3ddc72a2506c15212

build:
  number: 0
  noarch: python
  script:
    env:
      SKIP_HATCH_JS: "1"
    content:
      - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-js
  run:
    - python >=${{ python_min }}
    - spaday >=0.11.1,<1.0

tests:
  - python:
      imports:
        - spaday_lightweight_charts
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  license: Apache-2.0
  license_file: LICENSE
  summary: TradingView Lightweight Charts for spaday
  homepage: https://github.com/1kbgz/spaday-lightweight-charts
  repository: https://github.com/1kbgz/spaday-lightweight-charts

extra:
  recipe-maintainers:
    - timkpaine
